# Generated by Django 4.1.5 on 2023-02-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/posts')),
            ],
        ),
    ]
