# Generated by Django 4.1.5 on 2023-02-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_housepost_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepost',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housepost',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
