# Generated by Django 4.1.5 on 2023-01-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clientfeedback_contact_alter_aboutapartment_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
